steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f', 'Dockerfile.builder',  '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:builder', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:builder', '.']
- name: 'docker/compose:1.19.0'
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'REPO_NAME=$REPO_NAME'
  args: ['up', '--exit-code-from', 'test', 'test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:builder', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
