version: "3"
services:
  test:
    image: "gcr.io/${PROJECT_ID}/${REPO_NAME}:builder"
    build:
      args: [target, builder, cache-from, "gcr.io/${PROJECT_ID}/${REPO_NAME}:builder"]
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      go test ./...

